name: "A11y Testing"
description: "Run accessibility tests on a provided URL and spit out the info"
inputs:
  url:
    description: "Live URL of site to test"
    required: true
    default: "https://mysite.com"
  pages:
    description: "List of pages to test"
    required: false
    default: "['/', '/about', '/contact']"
  sitemap:
    description: "Sitemap of pages to test"
    required: false
outputs:
  results:
    description: "Results from pa11y tests"
    value: ${{steps.pa11y.outputs.results}}
runs:
  using: "composite"
  steps:
    - run: echo "running rests on ${{inputs.url}}"
      shell: bash
    - run: npm install -g pa11y-ci
      shell: bash
    - run: ls -la && pwd
      shell: bash
    - id: pa11y
      # run: echo "results=$(pa11y-ci --sitemap-find https://aimhigherweb.design --sitemap-replace ${{inputs.url}} --sitemap-exclude /blog/*)" >> $GITHUB_OUTPUT
      run: pa11y-ci --config ./.pa11yci --https://aimhigherweb.design/sitemap/sitemap-0.xml --sitemap-find https://aimhigherweb.design --sitemap-replace ${{inputs.url}} --sitemap-exclude /blog/*
      shell: bash
